name: rfid_reader_sdk
description: RFID Reader SDK plugin for Flutter, providing seamless integration with RFID readers.
version: 0.0.1
homepage: https://github.com/Sivabalasubramaniamdeveloper/rfid_reader_sdk_package.git

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.datayaan.rfid_reader_sdk
        pluginClass: ZebraRfidReaderSdkPlugin
      ios:
        pluginClass: ZebraRfidReaderSdkPlugin

scripts:
  clean: |
    fvm flutter clean
    fvm flutter pub get
    cd example
    fvm flutter clean
    fvm flutter pub get
    cd ios
    pod install